---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: traefik-tls-conf
data:
  traefik.toml: |
    # insecureSkipVerify = true，backend(不卸载tls)443，e.g dashboard ingress rules
    insecureSkipVerify = true
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      ## http skip https 
      [entryPoints.http.redirect]
      #entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      ## trustedIPs --> X-Frowarded-*,default(all)
      #[entryPoints.http.forwardedHeaders]
      #trustedIPs = ["10.1.0.0/16", "172.20.0.0/16", "192.168.1.x"]
      [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
