apiVersion: v1
kind: ReplicationController
metadata:
  name: fortune
spec:
  replicas: 2
  selector:
    app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - image: luksa/fortune
        name: html-generator
        volumeMounts:
         - name: html
           mountPath: /var/htdocs
      - image: nginx:alpine
        name: html
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: html
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
spec:
  selector:
    app: fortune
  ports:
  - port: 80
    targetPort: 80
